name:                amethyst
version:             0.1.0.0
github:              "Innf107/amethyst"
license:             BSD-3-Clause
author:              "welltypedwitch"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/Innf107/amethyst#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- mtl
- vector
- directory
- filepath
- megaparsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Werror=incomplete-patterns

library:
  source-dirs: src

executables:
  amethyst:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amethyst

tests:
  amethyst-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amethyst

language: GHC2021

default-extensions:
- NoImplicitPrelude
- StrictData
- LambdaCase
- DerivingStrategies
- BlockArguments
- OverloadedStrings
- OverloadedLists
- OverloadedRecordDot
- NoFieldSelectors
- DuplicateRecordFields
- DataKinds
- TypeFamilies
- RecordWildCards
