name:                sirius
version:             0.1.0.0
github:              "githubuser/sirius"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sirius#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- mtl
- vector
- directory
- filepath
- megaparsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Werror=incomplete-patterns

library:
  source-dirs: src

executables:
  sirius:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sirius

tests:
  sirius-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sirius

language: GHC2021

default-extensions:
- NoImplicitPrelude
- LambdaCase
- DerivingStrategies
- BlockArguments
- OverloadedStrings
- OverloadedLists
- OverloadedRecordDot
- NoFieldSelectors
- DuplicateRecordFields
- DataKinds
- TypeFamilies
